# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm i
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
        env:
          CI: true
